import { useContext } from "react";

import { SetTacticType } from ".";
import { AppContext } from "../../context/AppContext";
import {
  attackGroup,
  dmGroup,
  dmzGroup,
  fvaGroup,
  keeperGroup,
  maGroup,
  mGroup,
  mzGroup,
  omaGroup,
  omcGroup,
  vaGroup,
  vGroup,
  vzGroup,
} from "../../helpers/roles";
import { Tactic } from "../../types/tactics";
import { TacticsGridEntry } from "./TacticsGridEntry";

export const TacticsGrid = ({
  tactic,
  setTactic,
}: {
  tactic: Tactic | undefined;
  setTactic: SetTacticType;
}) => {
  const { primaryDataSet } = useContext(AppContext);

  return (
    <div className="grid grid-cols-7 w-full border border-black gap-1 p-1 m-1">
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={attackGroup}
          position={"STZL"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={attackGroup}
          position={"STZ"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={attackGroup}
          position={"STZR"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={omaGroup}
          position={"OML"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={omcGroup}
          position={"OMZL"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={omcGroup}
          position={"OM"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={omcGroup}
          position={"OMZR"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={omaGroup}
          position={"OMR"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>{" "}
      <div>
        <TacticsGridEntry
          allowedRoles={maGroup}
          position={"ML"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={mzGroup}
          position={"MZL"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={mGroup}
          position={"MZ"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={mzGroup}
          position={"MZR"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={maGroup}
          position={"MR"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={fvaGroup}
          position={"FVL"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={dmzGroup}
          position={"DMZL"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={dmGroup}
          position={"DM"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={dmzGroup}
          position={"DMZR"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={fvaGroup}
          position={"FVR"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={vaGroup}
          position={"VL"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={vzGroup}
          position={"VZL"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={vGroup}
          position={"VZ"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>
        <TacticsGridEntry
          allowedRoles={vzGroup}
          position={"VZR"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <TacticsGridEntry
        allowedRoles={vaGroup}
        position={"VR"}
        content={primaryDataSet}
        tactic={tactic}
        setTactic={setTactic}
      />
      <div>&nbsp;</div>
      <div>&nbsp;</div>
      <div>&nbsp;</div>
      <div>
        <TacticsGridEntry
          allowedRoles={keeperGroup}
          position={"TW"}
          content={primaryDataSet}
          tactic={tactic}
          setTactic={setTactic}
        />
      </div>
      <div>&nbsp;</div>
      <div>&nbsp;</div>
      <div>&nbsp;</div>
    </div>
  );
};
